# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mfg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='shipping_date',
            field=models.DateField(),
        ),
    ]
